-- Supabase migration for Campo Master Pack table.
-- Run this in the Supabase SQL Editor with table-owner privileges.
-- It preserves the existing sales_forward_look data/status columns, then adds all CSV headers from:
-- 0.0 Campo Caribe Data V5 10.01-36.csv

do $$
begin
  if to_regclass('public.master_pack') is null and to_regclass('public.sales_forward_look') is not null then
    alter table public.sales_forward_look rename to master_pack;
  end if;
end $$;

-- CSV headers
alter table public.master_pack add column if not exists "Batch Run Code" text;
alter table public.master_pack add column if not exists "Best if Used By Date:" text;
alter table public.master_pack add column if not exists "Product Quality Date" text;
alter table public.master_pack add column if not exists "Seed Batch Code 1" text;
alter table public.master_pack add column if not exists "Seed Batch Code 2" text;
alter table public.master_pack add column if not exists "Seed Batch Code 3" text;
alter table public.master_pack add column if not exists "Batch Run Date" text;
alter table public.master_pack add column if not exists "Pack Team Start" text;
alter table public.master_pack add column if not exists "Pack Team Finish" text;
alter table public.master_pack add column if not exists "Pack Week" text;
alter table public.master_pack add column if not exists "Julian Date" text;
alter table public.master_pack add column if not exists "Run #" text;
alter table public.master_pack add column if not exists "Pack # de Personas Run #1" text;
alter table public.master_pack add column if not exists "Pack Run #1 Inicio" text;
alter table public.master_pack add column if not exists "Pack Run #1 Final" text;
alter table public.master_pack add column if not exists "Pack # de Personas Run #2" text;
alter table public.master_pack add column if not exists "Pack Run #2 Inico" text;
alter table public.master_pack add column if not exists "Pack Run #2 Final" text;
alter table public.master_pack add column if not exists " Packing Down Time" text;
alter table public.master_pack add column if not exists "Packing Porque DownTime" text;
alter table public.master_pack add column if not exists "Total Pack Tiempo Transcurido" text;
alter table public.master_pack add column if not exists "Total # de personas Pack" text;
alter table public.master_pack add column if not exists "SKU Packed" text;
alter table public.master_pack add column if not exists "Quantity of Cases Packed" text;
alter table public.master_pack add column if not exists "Total Packed Weight" text;
alter table public.master_pack add column if not exists "Packed Case Size" text;
alter table public.master_pack add column if not exists "Total # de Personas" text;
alter table public.master_pack add column if not exists "Ronda 1 # of People QC " text;
alter table public.master_pack add column if not exists "Ronda #1 QC Inicio" text;
alter table public.master_pack add column if not exists "Ronda #1 QC End" text;
alter table public.master_pack add column if not exists "Ronda #2  of People QC" text;
alter table public.master_pack add column if not exists "Ronda #2 QC Start" text;
alter table public.master_pack add column if not exists "Ronda #2 QC End" text;
alter table public.master_pack add column if not exists "Total # de Personas QC" text;
alter table public.master_pack add column if not exists "Total Tiempo Transcurrido QC" text;
alter table public.master_pack add column if not exists "Unpacked Waste" text;
alter table public.master_pack add column if not exists "Pack Reason for Waste" text;
alter table public.master_pack add column if not exists "Pack Quality/Calidad" text;
alter table public.master_pack add column if not exists "Pack Multivac Waste" text;
alter table public.master_pack add column if not exists "Pack Temperatura del cuarto *F" text;
alter table public.master_pack add column if not exists "Pack Cleaning Start " text;
alter table public.master_pack add column if not exists "Pack Cleaning Finish" text;
alter table public.master_pack add column if not exists "Pack Prep start" text;
alter table public.master_pack add column if not exists "Pack Prep Finish" text;
alter table public.master_pack add column if not exists "Pack Absent Workers" text;
alter table public.master_pack add column if not exists "Pack Break 1 Start" text;
alter table public.master_pack add column if not exists "Pack Break 1 Finish" text;
alter table public.master_pack add column if not exists "Pack Lunch Start" text;
alter table public.master_pack add column if not exists "Pack Lunch Finish" text;
alter table public.master_pack add column if not exists "Pack Break 2 Start" text;
alter table public.master_pack add column if not exists "Pack Break 2 Finish" text;
alter table public.master_pack add column if not exists "Comments" text;
alter table public.master_pack add column if not exists "Pack Extra" text;
alter table public.master_pack add column if not exists "Ship Team Start" text;
alter table public.master_pack add column if not exists "Ship Team Finish" text;
alter table public.master_pack add column if not exists "Shipping Week" text;
alter table public.master_pack add column if not exists "Shipping Date" text;
alter table public.master_pack add column if not exists "Run Batch Shipped/Received" text;
alter table public.master_pack add column if not exists "Shipped or Received" text;
alter table public.master_pack add column if not exists "Shipping SKU" text;
alter table public.master_pack add column if not exists "Location Shipped " text;
alter table public.master_pack add column if not exists "Si Basura, Porque?" text;
alter table public.master_pack add column if not exists "# of Cases Shipped" text;
alter table public.master_pack add column if not exists "# Lbs Shipped" text;
alter table public.master_pack add column if not exists "# Palletas Shipped" text;
alter table public.master_pack add column if not exists "Food Safety Varification Check" text;
alter table public.master_pack add column if not exists "Truck Temp.(F)" text;
alter table public.master_pack add column if not exists "# of Workers" text;
alter table public.master_pack add column if not exists "Absent Workers" text;
alter table public.master_pack add column if not exists "Temperatura Almacen AM (F)" text;
alter table public.master_pack add column if not exists "Temperatura Almacen PM" text;
alter table public.master_pack add column if not exists "Ship Start" text;
alter table public.master_pack add column if not exists "Ship Finish" text;
alter table public.master_pack add column if not exists "Prep Start" text;
alter table public.master_pack add column if not exists "Prep Finish" text;
alter table public.master_pack add column if not exists "Cleaning Start" text;
alter table public.master_pack add column if not exists "Cleaning Finish" text;
alter table public.master_pack add column if not exists "Break 1 Start" text;
alter table public.master_pack add column if not exists "Break 1 Finish" text;
alter table public.master_pack add column if not exists "Lunch Start" text;
alter table public.master_pack add column if not exists "Lunch Finish" text;
alter table public.master_pack add column if not exists "Break 2 Start" text;
alter table public.master_pack add column if not exists "Break 2 Finish" text;
alter table public.master_pack add column if not exists "Shipping Comments" text;
alter table public.master_pack add column if not exists "Shipping Extra" text;
alter table public.master_pack add column if not exists "Warehouse Date" text;
alter table public.master_pack add column if not exists "W Batch Run Code" text;
alter table public.master_pack add column if not exists "Warehouse Location" text;
alter table public.master_pack add column if not exists "Cases in Inventory" text;
alter table public.master_pack add column if not exists "Cases Reserved" text;
alter table public.master_pack add column if not exists "Cases Available" text;
alter table public.master_pack add column if not exists "Cutomer Reserved" text;
alter table public.master_pack add column if not exists "Warehouse Observations" text;
alter table public.master_pack add column if not exists "Warehouse Pack Date" text;
alter table public.master_pack add column if not exists "Warehouse Age" text;
alter table public.master_pack add column if not exists "Warehouse SKU" text;
alter table public.master_pack add column if not exists "Warehouse Cosmments" text;
alter table public.master_pack add column if not exists "Sales Invoice Date" text;
alter table public.master_pack add column if not exists "Sale PO Date" text;
alter table public.master_pack add column if not exists "Sales Ship Via" text;
alter table public.master_pack add column if not exists "Sales Week" text;
alter table public.master_pack add column if not exists "Sales Ship Week" text;
alter table public.master_pack add column if not exists "Sales Ship Date" text;
alter table public.master_pack add column if not exists "Sales Invoice No." text;
alter table public.master_pack add column if not exists "Sales SKU" text;
alter table public.master_pack add column if not exists "Sales # of Cases" text;
alter table public.master_pack add column if not exists "Sales Lbs. Per Case" text;
alter table public.master_pack add column if not exists "Sales Lbs Eq." text;
alter table public.master_pack add column if not exists "Sales Destination" text;
alter table public.master_pack add column if not exists "Sales Customer" text;
alter table public.master_pack add column if not exists "Sales Term" text;
alter table public.master_pack add column if not exists "Sales Extra" text;
alter table public.master_pack add column if not exists "Dia Ausente" text;
alter table public.master_pack add column if not exists "HR Departamento" text;
alter table public.master_pack add column if not exists "HR Persona Ausente" text;
alter table public.master_pack add column if not exists "HR Porque Ausente" text;
alter table public.master_pack add column if not exists "HR Excused" text;
alter table public.master_pack add column if not exists "Pack Nombre del Empleado" text;
alter table public.master_pack add column if not exists "Pack Fecha Performance" text;
alter table public.master_pack add column if not exists "Incoming Quality H1" text;
alter table public.master_pack add column if not exists "H1 7:30-8:30" text;
alter table public.master_pack add column if not exists "Incoming Quality H2" text;
alter table public.master_pack add column if not exists "H2 8:30-9:30" text;
alter table public.master_pack add column if not exists "Incoming Quality H3" text;
alter table public.master_pack add column if not exists "H3 9:30-10:30" text;
alter table public.master_pack add column if not exists "Incoming Quality H4" text;
alter table public.master_pack add column if not exists "H4 10:30-11:00" text;
alter table public.master_pack add column if not exists "Incoming Quality H5" text;
alter table public.master_pack add column if not exists "H5 11:30-12:00" text;
alter table public.master_pack add column if not exists "Incoming Quality H6" text;
alter table public.master_pack add column if not exists "H6 12:30-1:30" text;
alter table public.master_pack add column if not exists "Incoming Quality H7" text;
alter table public.master_pack add column if not exists "H7 1:30-2:30" text;
alter table public.master_pack add column if not exists "Incoming Quality 8" text;
alter table public.master_pack add column if not exists "H8 2:30-3:30" text;
alter table public.master_pack add column if not exists "Incoming Quality Total" text;
alter table public.master_pack add column if not exists "Pack Hr" text;
alter table public.master_pack add column if not exists "Pack Canst/Hr" text;
alter table public.master_pack add column if not exists "Yamato Date" text;
alter table public.master_pack add column if not exists "Yamato Clamshell Type" text;
alter table public.master_pack add column if not exists "Yamato Start Time" text;
alter table public.master_pack add column if not exists "Yamato End Time" text;
alter table public.master_pack add column if not exists "Yamato Total Dumps" text;
alter table public.master_pack add column if not exists "Yamato # of People" text;
alter table public.master_pack add column if not exists "Sanitation Nombre Empleado" text;
alter table public.master_pack add column if not exists "Sanitation Date" text;
alter table public.master_pack add column if not exists "H1: 7:00-8:00" text;
alter table public.master_pack add column if not exists "H2: 8:00-9:00" text;
alter table public.master_pack add column if not exists "H3: 9:00-10:00" text;
alter table public.master_pack add column if not exists "H4: 10:00-11:00" text;
alter table public.master_pack add column if not exists "H5: 11:00-12:00" text;
alter table public.master_pack add column if not exists "H6: 12:30-1:30" text;
alter table public.master_pack add column if not exists "H7: 1:30-2:30" text;
alter table public.master_pack add column if not exists "H8:2:30-3:00" text;
alter table public.master_pack add column if not exists "Sanitation Total Performance" text;
alter table public.master_pack add column if not exists "Sanitation Name Canasta Performance" text;
alter table public.master_pack add column if not exists "H1 7:00-8:00" text;
alter table public.master_pack add column if not exists "H2 8:00-9:00" text;
alter table public.master_pack add column if not exists "H3 9:00-10:00" text;
alter table public.master_pack add column if not exists "H4 10:00-11:00" text;
alter table public.master_pack add column if not exists "H5 11:00-12:00" text;
alter table public.master_pack add column if not exists "H6 12:30-1:30" text;
alter table public.master_pack add column if not exists "H7 1:30-2:30" text;
alter table public.master_pack add column if not exists "H8 2:30-3:30" text;
alter table public.master_pack add column if not exists "Total Canastas por hora" text;
alter table public.master_pack add column if not exists "Sanitation Quimicos Fecha" text;
alter table public.master_pack add column if not exists "Nombre" text;
alter table public.master_pack add column if not exists "Departamento" text;
alter table public.master_pack add column if not exists "Tanques" text;
alter table public.master_pack add column if not exists "Galones" text;
alter table public.master_pack add column if not exists "Quimico utilizado" text;

-- Dashboard workflow fields retained outside the CSV contract.
alter table public.master_pack add column if not exists "Order Received" boolean;
alter table public.master_pack add column if not exists "Order Received Name" text;
alter table public.master_pack add column if not exists "Pack Preparations" boolean;
alter table public.master_pack add column if not exists "Pack Preparations Name" text;
alter table public.master_pack add column if not exists "Order Complete" boolean;
alter table public.master_pack add column if not exists "Order Complete Name" text;
alter table public.master_pack add column if not exists "Order Shipped" boolean;
alter table public.master_pack add column if not exists "Order Shipped Name" text;

notify pgrst, 'reload schema';
